using System.Collections.Generic;

namespace MPT.CSI.Serialize.SAP2000
{
    internal class SAP2000Tables : ProgramTables
    {
        public const string ACTIVE_DEGREES_OF_FREEDOM = "ACTIVE DEGREES OF FREEDOM";
        public const string ANALYSIS_OPTIONS = "ANALYSIS OPTIONS";
        public const string AREA_LOADS_UNIFORM = "AREA LOADS - UNIFORM";
        public const string AREA_LOADS_WIND_PRESSURE_COEFFICIENTS = "AREA LOADS - WIND PRESSURE COEFFICIENTS";
        public const string AREA_SECTION_ASSIGNMENTS = "AREA SECTION ASSIGNMENTS";
        public const string AREA_SECTION_PROPERTIES = "AREA SECTION PROPERTIES";
        public const string AREA_SECTION_PROPERTY_DESIGN_PARAMETERS = "AREA SECTION PROPERTY DESIGN PARAMETERS";
        public const string AREA_SECTION_PROPERTY_LAYERS = "AREA SECTION PROPERTY LAYERS";
        public const string AREA_SECTION_PROPERTY_TIME_DEPENDENT = "AREA SECTION PROPERTY - TIME DEPENDENT";
        public const string AREA_STIFFNESS_MODIFIERS = "AREA STIFFNESS MODIFIERS";
        public const string AUTO_COMBINATION_OPTION_DATA_01_GENERAL = "AUTO COMBINATION OPTION DATA 01 - GENERAL";
        public const string AUTO_WAVE_3_WAVE_CHARACTERISTICS_GENERAL = "AUTO WAVE 3 - WAVE CHARACTERISTICS - GENERAL";
        public const string CABLE_OUTPUT_STATION_ASSIGNMENTS = "CABLE OUTPUT STATION ASSIGNMENTS";
        public const string CABLE_SECTION_ASSIGNMENTS = "CABLE SECTION ASSIGNMENTS";
        public const string CABLE_SECTION_DEFINITIONS = "CABLE SECTION DEFINITIONS";
        public const string CABLE_SHAPE_DATA = "CABLE SHAPE DATA";
        public const string CASE_STATIC_1_LOAD_ASSIGNMENTS = "CASE - STATIC 1 - LOAD ASSIGNMENTS";
        public const string CASE_STATIC_2_NONLINEAR_LOAD_APPLICATION = "CASE - STATIC 2 - NONLINEAR LOAD APPLICATION";
        public const string CASE_STATIC_4_NONLINEAR_PARAMETERS = "CASE - STATIC 4 - NONLINEAR PARAMETERS";
        public const string CASE_STATIC_5_NONLINEAR_STAGE_DEFINITIONS = "CASE - STATIC 5 - NONLINEAR STAGE DEFINITIONS";
        public const string CASE_STATIC_6_NONLINEAR_STAGE_DATA = "CASE - STATIC 6 - NONLINEAR STAGE DATA";
        public const string CASE_STATIC_7_ADDITIONAL_CONTROLLED_DISPLACEMENTS = "CASE - STATIC 7 - ADDITIONAL CONTROLLED DISPLACEMENTS";
        public const string CASE_DIRECT_HISTORY_1_GENERAL = "CASE - DIRECT HISTORY 1 - GENERAL";
        public const string CASE_DIRECT_HISTORY_2_LOAD_ASSIGNMENTS = "CASE - DIRECT HISTORY 2 - LOAD ASSIGNMENTS";
        public const string CASE_DIRECT_HISTORY_3_VISCOUS_PROPORTIONAL_DAMPING = "CASE - DIRECT HISTORY 3 - VISCOUS PROPORTIONAL DAMPING";
        public const string CASE_DIRECT_HISTORY_4_INTEGRATION_PARAMETERS = "CASE - DIRECT HISTORY 4 - INTEGRATION PARAMETERS";
        public const string CASE_DIRECT_HISTORY_5_NONLINEAR_PARAMETERS = "CASE - DIRECT HISTORY 5 - NONLINEAR PARAMETERS";
        public const string CASE_DIRECT_HISTORY_7_MODAL_PROPORTIONAL_DAMPING = "CASE - DIRECT HISTORY 7 - MODAL INTERPOLATED DAMPING";
        public const string CASE_DIRECT_HISTORY_8_MODAL_DAMPING_OVERRIDES = "CASE - DIRECT HISTORY 8 - MODAL DAMPING OVERRIDES";
        public const string CASE_FREQUENCY_HISTORY_1_GENERAL = "CASE - FREQUENCY HISTORY 1 - GENERAL";
        public const string CASE_FREQUENCY_HISTORY_2_LOAD_ASSIGNMENTS = "CASE - FREQUENCY HISTORY 2 - LOAD ASSIGNMENTS";
        public const string CASE_FREQUENCY_HISTORY_3_CONSTANT_DAMPING = "CASE - FREQUENCY HISTORY 3 - CONSTANT DAMPING";
        public const string CASE_FREQUENCY_HISTORY_5_INTEGRATION_PARAMETERS = "CASE - FREQUENCY HISTORY 5 - INTEGRATION PARAMETERS";
        public const string CASE_MODAL_HISTORY_1_GENERAL = "CASE - MODAL HISTORY 1 - GENERAL";
        public const string CASE_MODAL_HISTORY_2_LOAD_ASSIGNMENTS = "CASE - MODAL HISTORY 2 - LOAD ASSIGNMENTS";
        public const string CASE_MODAL_HISTORY_3_INTERPOLATED_DAMPING = "CASE - MODAL HISTORY 3 - INTERPOLATED DAMPING";
        public const string CASE_MODAL_HISTORY_4_PROPORTIONAL_DAMPING = "CASE - MODAL HISTORY 4 - PROPORTIONAL DAMPING";
        public const string CASE_MODAL_HISTORY_5_DAMPING_OVERRIDES = "CASE - MODAL HISTORY 5 - DAMPING OVERRIDES";
        public const string CASE_MODAL_HISTORY_6_NONLINEAR_PARAMETERS = "CASE - MODAL HISTORY 6 - NONLINEAR PARAMETERS";
        public const string CASE_MODAL_1_GENERAL = "CASE - MODAL 1 - GENERAL";
        public const string CASE_MODAL_2_LOAD_ASSIGNMENTS_EIGEN = "CASE - MODAL 2 - LOAD ASSIGNMENTS - EIGEN";
        public const string CASE_MODAL_3_LOAD_ASSIGNMENTS_RITZ = "CASE - MODAL 3 - LOAD ASSIGNMENTS - RITZ";
        public const string CASE_RESPONSE_SPECTRUM_1_GENERAL = "CASE - RESPONSE SPECTRUM 1 - GENERAL";
        public const string CASE_RESPONSE_SPECTRUM_2_LOAD_ASSIGNMENTS = "CASE - RESPONSE SPECTRUM 2 - LOAD ASSIGNMENTS";
        public const string CASE_RESPONSE_SPECTRUM_3_INTERPOLATED_DAMPING ="CASE - RESPONSE SPECTRUM 3 - INTERPOLATED DAMPING";
        public const string CASE_RESPONSE_SPECTRUM_4_PROPORTIONAL_DAMPING ="CASE - RESPONSE SPECTRUM 4 - PROPORTIONAL DAMPING";
        public const string CASE_RESPONSE_SPECTRUM_5_DAMPING_OVERRIDES ="CASE - RESPONSE SPECTRUM 5 - DAMPING OVERRIDES";
        public const string CASE_RESPONSE_SPECTRUM_6_ECCENTRICITY_OVERRIDES = "CASE - RESPONSE SPECTRUM 6 - ECCENTRICITY OVERRIDES";
        public const string COMBINATION_DEFINITIONS = "COMBINATION DEFINITIONS";
        public const string CONNECTIVITY_AREA = "CONNECTIVITY - AREA";
        public const string CONNECTIVITY_CABLE = "CONNECTIVITY - CABLE";
        public const string CONNECTIVITY_FRAME = "CONNECTIVITY - FRAME";
        public const string CONNECTIVITY_SOLID = "CONNECTIVITY - SOLID";
        public const string CONNECTIVITY_LINK = "CONNECTIVITY - LINK";
        public const string CONNECTIVITY_TENDON = "CONNECTIVITY - TENDON";
        public const string COORDINATE_SYSTEMS = "COORDINATE SYSTEMS";
        public const string DATABASE_DOCUMENTATION = "DATABASE DOCUMENTATION";
        public const string DATABASE_FORMAT_TYPES = "DATABASE FORMAT TYPES";
        public const string FRAME_AUTO_MESH_ASSIGNMENTS = "FRAME AUTO MESH ASSIGNMENTS";
        public const string FRAME_DESIGN_PROCEDURES = "FRAME DESIGN PROCEDURES";
        public const string FRAME_HINGE_ASSIGNS_02_USER_DEFINED_PROPERTIES = "FRAME HINGE ASSIGNS 02 - USER DEFINED PROPERTIES";
        public const string FRAME_HINGE_ASSIGNS_09_HINGE_OVERWRITES = "FRAME HINGE ASSIGNS 09 - HINGE OVERWRITES";
        public const string FRAME_HINGE_ASSIGNS_12_AUTO_ASCE_41_13_STEEL_BEAM = "FRAME HINGE ASSIGNS 12 - AUTO ASCE 41-13 - STEEL BEAM";
        public const string FRAME_INSERTION_POINT_ASSIGNMENTS = "FRAME INSERTION POINT ASSIGNMENTS";
        public const string FRAME_LOAD_TRANSFER_OPTIONS = "FRAME LOAD TRANSFER OPTIONS";
        public const string FRAME_LOADS_POINT = "FRAME LOADS - POINT";
        public const string FRAME_LOADS_DISTRIBUTED = "FRAME LOADS - DISTRIBUTED";
        public const string FRAME_OUTPUT_STATION_ASSIGNMENTS = "FRAME OUTPUT STATION ASSIGNMENTS";
        public const string FRAME_PROPERTY_MODIFIERS = "FRAME PROPERTY MODIFIERS";
        public const string FRAME_RELEASE_ASSIGNMENTS_1_GENERAL = "FRAME RELEASE ASSIGNMENTS 1 - GENERAL";
        public const string FRAME_RELEASE_ASSIGNMENTS_2_PARTIAL_FIXITY = "FRAME RELEASE ASSIGNMENTS 2 - PARTIAL FIXITY";
        public const string FRAME_SECTION_ASSIGNMENTS = "FRAME SECTION ASSIGNMENTS";
        public const string FRAME_SECTION_PROPERTIES_01_GENERAL = "FRAME SECTION PROPERTIES 01 - GENERAL";
        public const string FRAME_SECTION_PROPERTIES_02_CONCRETE_COLUMN = "FRAME SECTION PROPERTIES 02 - CONCRETE COLUMN";
        public const string FRAME_SECTION_PROPERTIES_03_CONCRETE_BEAM = "FRAME SECTION PROPERTIES 03 - CONCRETE BEAM";
        public const string FRAME_SECTION_PROPERTIES_04_AUTO_SELECT = "FRAME SECTION PROPERTIES 04 - AUTO SELECT";
        public const string FRAME_SECTION_PROPERTIES_05_NONPRISMATIC = "FRAME SECTION PROPERTIES 05 - NONPRISMATIC";
        public const string FRAME_SECTION_PROPERTIES_07_BUILT_UP_I = "FRAME SECTION PROPERTIES 07 - BUILT UP I";
        public const string FRAME_SECTION_PROPERTIES_10_STEEL_JOIST_GENERAL = "FRAME SECTION PROPERTIES 10 - STEEL JOIST GENERAL";
        public const string FRAME_SECTION_PROPERTIES_11_STEEL_JOIST_DATA = "FRAME SECTION PROPERTIES 11 - STEEL JOIST DATA";
        public const string FRAME_SECTION_PROPERTIES_13_TIME_DEPENDENT = "FRAME SECTION PROPERTIES 13 - TIME DEPENDENT";
        public const string FUNCTION_PLOT_FUNCTIONS = "FUNCTION - PLOT FUNCTIONS";
        public const string FUNCTION_POWER_SPECTRAL_DENSITY_USER = "FUNCTION - POWER SPECTRAL DENSITY - USER";
        public const string FUNCTION_RESPONSE_SPECTRUM_USER = "FUNCTION - RESPONSE SPECTRUM - USER";
        public const string FUNCTION_STEADY_STATE_USER = "FUNCTION - STEADY STATE - USER";
        public const string FUNCTION_TIME_HISTORY_COSINE = "FUNCTION - TIME HISTORY - COSINE";
        public const string FUNCTION_TIME_HISTORY_RAMP = "FUNCTION - TIME HISTORY - RAMP";
        public const string FUNCTION_TIME_HISTORY_SAWTOOTH = "FUNCTION - TIME HISTORY - SAWTOOTH";
        public const string FUNCTION_TIME_HISTORY_SINE = "FUNCTION - TIME HISTORY - SINE";
        public const string FUNCTION_TIME_HISTORY_TRIANGULAR = "FUNCTION - TIME HISTORY - TRIANGULAR";
        public const string FUNCTION_TIME_HISTORY_USER = "FUNCTION - TIME HISTORY - USER";
        public const string FUNCTION_RESPONSE_SPECTRUM_UBC97 = "FUNCTION - RESPONSE SPECTRUM - UBC97";
        public const string GRID_LINES = "GRID LINES";
        public const string GROUPS_1_DEFINITIONS = "GROUPS 1 - DEFINITIONS";
        public const string GROUPS_2_ASSIGNMENTS = "GROUPS 2 - ASSIGNMENTS";
        public const string JOINT_COORDINATES = "JOINT COORDINATES";
        public const string JOINT_PATTERN_DEFINITIONS = "JOINT PATTERN DEFINITIONS";
        public const string JOINT_RESTRAINT_ASSIGNMENTS = "JOINT RESTRAINT ASSIGNMENTS";
        public const string JOINT_CONSTRAINT_ASSIGNMENTS = "JOINT CONSTRAINT ASSIGNMENTS";
        public const string JOINT_ADDED_MASS_ASSIGNMENTS = "JOINT ADDED MASS ASSIGNMENTS";
        public const string JOINT_LOCAL_AXES_ASSIGNMENTS_1_TYPICAL = "JOINT LOCAL AXES ASSIGNMENTS 1 - TYPICAL";
        public const string JOINT_LOCAL_AXES_ASSIGNMENTS_2_ADVANCED = "JOINT LOCAL AXES ASSIGNMENTS 2 - ADVANCED";
        public const string JOINT_MERGE_NUMBER_ASSIGNMENTS = "JOINT MERGE NUMBER ASSIGNMENTS";
        public const string JOINT_PANEL_ZONE_ASSIGNMENTS = "JOINT PANEL ZONE ASSIGNMENTS";
        public const string JOINT_SPRING_ASSIGNMENTS_1_UNCOUPLED = "JOINT SPRING ASSIGNMENTS 1 - UNCOUPLED";
        public const string JOINT_SPRING_ASSIGNMENTS_2_COUPLED = "JOINT SPRING ASSIGNMENTS 2 - COUPLED";
        public const string JOINT_LOADS_FORCE = "JOINT LOADS - FORCE";
        public const string JOINT_LOADS_GROUND_DISPLACEMENT = "JOINT LOADS - GROUND DISPLACEMENT";
        public const string LINK_PROPERTY_DEFINITIONS_01_GENERAL = "LINK PROPERTY DEFINITIONS 01 - GENERAL";
        public const string LINK_PROPERTY_DEFINITIONS_02_LINEAR = "LINK PROPERTY DEFINITIONS 02 - LINEAR";
        public const string LINK_PROPERTY_DEFINITIONS_03_MULTILINEAR = "LINK PROPERTY DEFINITIONS 03 - MULTILINEAR";
        public const string LINK_PROPERTY_ASSIGNMENTS = "LINK PROPERTY ASSIGNMENTS";
        public const string LOAD_CASE_DEFINITIONS = "LOAD CASE DEFINITIONS";
        public const string LOAD_PATTERN_DEFINITIONS = "LOAD PATTERN DEFINITIONS";
        public const string MASS_SOURCE = "MASS SOURCE";
        public const string MATERIAL_PROPERTIES_01_GENERAL = "MATERIAL PROPERTIES 01 - GENERAL";
        public const string MATERIAL_PROPERTIES_01T_MATERIAL_TEMPERATURES = "MATERIAL PROPERTIES 01T - MATERIAL TEMPERATURES";
        public const string MATERIAL_PROPERTIES_02_BASIC_MECHANICAL_PROPERTIES = "MATERIAL PROPERTIES 02 - BASIC MECHANICAL PROPERTIES";
        public const string MATERIAL_PROPERTIES_03A_STEEL_DATA = "MATERIAL PROPERTIES 03A - STEEL DATA";
        public const string MATERIAL_PROPERTIES_03B_CONCRETE_DATA = "MATERIAL PROPERTIES 03B - CONCRETE DATA";
        public const string MATERIAL_PROPERTIES_03C_ALUMINUM_DATA = "MATERIAL PROPERTIES 03C - ALUMINUM DATA";
        public const string MATERIAL_PROPERTIES_03D_COLD_FORMED_DATA = "MATERIAL PROPERTIES 03D - COLD FORMED DATA";
        public const string MATERIAL_PROPERTIES_03E_REBAR_DATA = "MATERIAL PROPERTIES 03E - REBAR DATA";
        public const string MATERIAL_PROPERTIES_03F_TENDON_DATA = "MATERIAL PROPERTIES 03F - TENDON DATA";
        public const string MATERIAL_PROPERTIES_03G_OTHER_DATA = "MATERIAL PROPERTIES 03G - OTHER DATA";
        public const string MATERIAL_PROPERTIES_04_USER_STRESS_STRAIN_CURVES = "MATERIAL PROPERTIES 04 - USER STRESS-STRAIN CURVES";
        public const string MATERIAL_PROPERTIES_06_DAMPING_PARAMETERS = "MATERIAL PROPERTIES 06 - DAMPING PARAMETERS";
        public const string NAMED_SETS_DATABASE_TABLES_1_GENERAL = "NAMED SETS - DATABASE TABLES 1 - GENERAL";
        public const string NAMED_SETS_DATABASE_TABLES_2_SELECTIONS = "NAMED SETS - DATABASE TABLES 2 - SELECTIONS";
        public const string OPTIONS_COLORS_DISPLAY = "OPTIONS - COLORS - DISPLAY";
        public const string OPTIONS_COLORS_OUTPUT = "OPTIONS - COLORS - OUTPUT";
        public const string OVERWRITES_ALUMINUM_DESIGN_AA_ASD_2000 = "OVERWRITES - ALUMINUM DESIGN - AA-ASD 2000";
        public const string OVERWRITES_ALUMINUM_DESIGN_AA_LRFD_2000 = "OVERWRITES - ALUMINUM DESIGN - AA-LRFD 2000";
        public const string OVERWRITES_COLD_FORMED_DESIGN_AISI_ASD96 = "OVERWRITES - COLD FORMED DESIGN - AISI-ASD96";
        public const string OVERWRITES_COLD_FORMED_DESIGN_AISI_LRFD96 = "OVERWRITES - COLD FORMED DESIGN - AISI-LRFD96";
        public const string OVERWRITES_CONCRETE_DESIGN_ACI_318_08_IBC_2009 = "OVERWRITES - CONCRETE DESIGN - ACI 318-08/IBC2009";
        public const string OVERWRITES_CONCRETE_DESIGN_ACI_318_11 = "OVERWRITES - CONCRETE DESIGN - ACI 318-11";
        public const string OVERWRITES_CONCRETE_DESIGN_ACI_318_14 = "OVERWRITES - CONCRETE DESIGN - ACI 318-14";
        public const string OVERWRITES_CONCRETE_DESIGN_AS_3600_09 = "OVERWRITES - CONCRETE DESIGN - AS 3600-09";
        public const string OVERWRITES_CONCRETE_DESIGN_AS_3600_18 = "OVERWRITES - CONCRETE DESIGN - AS 3600-18";
        public const string OVERWRITES_CONCRETE_DESIGN_BS8110_97 = "OVERWRITES - CONCRETE DESIGN - BS8110 97";
        public const string OVERWRITES_CONCRETE_DESIGN_CSA_A233_04 = "OVERWRITES - CONCRETE DESIGN - CSA-A233-04";
        public const string OVERWRITES_CONCRETE_DESIGN_CSA_A233_14 = "OVERWRITES - CONCRETE DESIGN - CSA-A233-14";
        public const string OVERWRITES_CONCRETE_DESIGN_EUROCODE_2_2004 = "OVERWRITES - CONCRETE DESIGN - EUROCODE 2-2004";
        public const string OVERWRITES_CONCRETE_DESIGN_HONG_KONG_CP_2013 = "OVERWRITES - CONCRETE DESIGN - HONG KONG CP 2013";
        public const string OVERWRITES_CONCRETE_DESIGN_INDIAN_IS_456_2000 = "OVERWRITES - CONCRETE DESIGN - INDIAN IS 456-200";
        public const string OVERWRITES_CONCRETE_DESIGN_ITALIAN_NTC_2008 = "OVERWRITES - CONCRETE DESIGN - ITALIAN NTC 2008";
        public const string OVERWRITES_CONCRETE_DESIGN_KBC_2009 = "OVERWRITES - CONCRETE DESIGN - KBC 2009";
        public const string OVERWRITES_CONCRETE_DESIGN_KBC_2016 = "OVERWRITES - CONCRETE DESIGN - KBC 2016";
        public const string OVERWRITES_CONCRETE_DESIGN_MEXICAN_RCDF_2004 = "OVERWRITES - CONCRETE DESIGN - MEXICAN RCDF 2004";
        public const string OVERWRITES_CONCRETE_DESIGN_MEXICAN_RCDF_2017 = "OVERWRITES - CONCRETE DESIGN - MEXICAN RCDF 2017";
        public const string OVERWRITES_CONCRETE_DESIGN_NZS_3101_06 = "OVERWRITES - CONCRETE DESIGN - NZS 3101-06";
        public const string OVERWRITES_CONCRETE_DESIGN_SINGAPORE_CP_65_99 = "OVERWRITES - CONCRETE DESIGN - SINGAPORE CP 65-99";
        public const string OVERWRITES_CONCRETE_DESIGN_TS_500_2000 = "OVERWRITES - CONCRETE DESIGN - TS 500-2000";
        public const string OVERWRITES_STEEL_DESIGN_AISC360_05_IBC2006 = "OVERWRITES - STEEL DESIGN - AISC360-05-IBC2006";
        public const string OVERWRITES_STEEL_DESIGN_AISC_360_10 = "OVERWRITES - STEEL DESIGN - AISC 360-10";
        public const string OVERWRITES_STEEL_DESIGN_AISC_360_16 = "OVERWRITES - STEEL DESIGN - AISC 360-16";
        public const string OVERWRITES_STEEL_DESIGN_AS_4100_1998 = "OVERWRITES - STEEL DESIGN - AS 4100-1998";
        public const string OVERWRITES_STEEL_DESIGN_BS5950_2000 = "OVERWRITES - STEEL DESIGN - BS5950 2000";
        public const string OVERWRITES_STEEL_DESIGN_CSA_S16_09 = "OVERWRITES - STEEL DESIGN - CSA-S16-09";
        public const string OVERWRITES_STEEL_DESIGN_CSA_S16_14 = "OVERWRITES - STEEL DESIGN - CSA S16-14";
        public const string OVERWRITES_STEEL_DESIGN_EUROCODE_3_2005 = "OVERWRITES - STEEL DESIGN - EUROCODE 3-2005";
        public const string OVERWRITES_STEEL_DESIGN_INDIAN_IS_800_2007 = "OVERWRITES - STEEL DESIGN - INDIAN IS 800:2007";
        public const string OVERWRITES_STEEL_DESIGN_ITALIAN_NTC_2008 = "OVERWRITES - STEEL DESIGN - ITALIAN NTC 2008";
        public const string OVERWRITES_STEEL_DESIGN_ITALIAN_NTC_2018 = "OVERWRITES - STEEL DESIGN - ITALIAN NTC 2018";
        public const string OVERWRITES_STEEL_DESIGN_KBC_2009 = "OVERWRITES - STEEL DESIGN - KBC 2009";
        public const string OVERWRITES_STEEL_DESIGN_NZS_3404_1997 = "OVERWRITES - STEEL DESIGN - NZS 3404-1997";
        public const string PREFERENCES_ALUMINUM_DESIGN_AA_ASD_2000 = "PREFERENCES - ALUMINUM DESIGN - AA-ASD 2000";
        public const string PREFERENCES_ALUMINUM_DESIGN_AA_LRFD_2000 = "PREFERENCES - ALUMINUM DESIGN - AA-LRFD 2000";
        public const string PREFERENCES_COLD_FORMED_DESIGN_AISI_ASD96 = "PREFERENCES - COLD FORMED DESIGN - AISI-ASD96";
        public const string PREFERENCES_COLD_FORMED_DESIGN_AISI_LRFD96 = "PREFERENCES - COLD FORMED DESIGN - AISI-LRFD96";
        public const string PREFERENCES_CONCRETE_DESIGN_ACI_318_08_IBC_2009 = "PREFERENCES - CONCRETE DESIGN - ACI 318-08/IBC2009";
        public const string PREFERENCES_CONCRETE_DESIGN_ACI_318_11 = "PREFERENCES - CONCRETE DESIGN - ACI 318-11";
        public const string PREFERENCES_CONCRETE_DESIGN_ACI_318_14 = "PREFERENCES - CONCRETE DESIGN - ACI 318-14";
        public const string PREFERENCES_CONCRETE_DESIGN_AS_3600_09 = "PREFERENCES - CONCRETE DESIGN - AS 3600-09";
        public const string PREFERENCES_CONCRETE_DESIGN_AS_3600_18 = "PREFERENCES - CONCRETE DESIGN - AS 3600-18";
        public const string PREFERENCES_CONCRETE_DESIGN_BS8110_97 = "PREFERENCES - CONCRETE DESIGN - BS8110 97";
        public const string PREFERENCES_CONCRETE_DESIGN_CSA_A233_04 = "PREFERENCES - CONCRETE DESIGN - CSA-A233-04";
        public const string PREFERENCES_CONCRETE_DESIGN_CSA_A233_14 = "PREFERENCES - CONCRETE DESIGN - CSA-A233-14";
        public const string PREFERENCES_CONCRETE_DESIGN_EUROCODE_2_2004 = "PREFERENCES - CONCRETE DESIGN - EUROCODE 2-2004";
        public const string PREFERENCES_CONCRETE_DESIGN_HONG_KONG_CP_2013 = "PREFERENCES - CONCRETE DESIGN - HONG KONG CP 2013";
        public const string PREFERENCES_CONCRETE_DESIGN_INDIAN_IS_456_2000 = "PREFERENCES - CONCRETE DESIGN - INDIAN IS 456-200";
        public const string PREFERENCES_CONCRETE_DESIGN_ITALIAN_NTC_2008 = "PREFERENCES - CONCRETE DESIGN - ITALIAN NTC 2008";
        public const string PREFERENCES_CONCRETE_DESIGN_KBC_2009 = "PREFERENCES - CONCRETE DESIGN - KBC 2009";
        public const string PREFERENCES_CONCRETE_DESIGN_KBC_2016 = "PREFERENCES - CONCRETE DESIGN - KBC 2016";
        public const string PREFERENCES_CONCRETE_DESIGN_MEXICAN_RCDF_2004 = "PREFERENCES - CONCRETE DESIGN - MEXICAN RCDF 2004";
        public const string PREFERENCES_CONCRETE_DESIGN_MEXICAN_RCDF_2017 = "PREFERENCES - CONCRETE DESIGN - MEXICAN RCDF 2017";
        public const string PREFERENCES_CONCRETE_DESIGN_NZS_3101_06 = "PREFERENCES - CONCRETE DESIGN - NZS 3101-06";
        public const string PREFERENCES_CONCRETE_DESIGN_SINGAPORE_CP_65_99 = "PREFERENCES - CONCRETE DESIGN - SINGAPORE CP 65-99";
        public const string PREFERENCES_CONCRETE_DESIGN_TS_500_2000 = "PREFERENCES - CONCRETE DESIGN - TS 500-2000";
        public const string PREFERENCES_DIMENSIONAL = "PREFERENCES - DIMENSIONAL";
        public const string PREFERENCES_STEEL_DESIGN_AISC360_05_IBC2006 = "PREFERENCES - STEEL DESIGN - AISC360-05-IBC2006";
        public const string PREFERENCES_STEEL_DESIGN_AISC_360_10 = "PREFERENCES - STEEL DESIGN - AISC 360-10";
        public const string PREFERENCES_STEEL_DESIGN_AISC_360_16 = "PREFERENCES - STEEL DESIGN - AISC 360-16";
        public const string PREFERENCES_STEEL_DESIGN_AS_4100_1998 = "PREFERENCES - STEEL DESIGN - AS 4100-1998";
        public const string PREFERENCES_STEEL_DESIGN_BS5950_2000 = "PREFERENCES - STEEL DESIGN - BS5950 2000";
        public const string PREFERENCES_STEEL_DESIGN_CSA_S16_09 = "PREFERENCES - STEEL DESIGN - CSA-S16-09";
        public const string PREFERENCES_STEEL_DESIGN_CSA_S16_14 = "PREFERENCES - STEEL DESIGN - CSA S16-14";
        public const string PREFERENCES_STEEL_DESIGN_EUROCODE_3_2005 = "PREFERENCES - STEEL DESIGN - EUROCODE 3-2005";
        public const string PREFERENCES_STEEL_DESIGN_INDIAN_IS_800_2007 = "PREFERENCES - STEEL DESIGN - INDIAN IS 800:2007";
        public const string PREFERENCES_STEEL_DESIGN_ITALIAN_NTC_2008 = "PREFERENCES - STEEL DESIGN - ITALIAN NTC 2008";
        public const string PREFERENCES_STEEL_DESIGN_ITALIAN_NTC_2018 = "PREFERENCES - STEEL DESIGN - ITALIAN NTC 2018";
        public const string PREFERENCES_STEEL_DESIGN_KBC_2009 = "PREFERENCES - STEEL DESIGN - KBC 2009";
        public const string PREFERENCES_STEEL_DESIGN_NZS_3404_1997 = "PREFERENCES - STEEL DESIGN - NZS 3404-1997";
        public const string PROGRAM_CONTROL = "PROGRAM CONTROL";
        public const string PROJECT_INFORMATION = "PROJECT INFORMATION";
        public const string REBAR_SIZES = "REBAR SIZES";
        public const string SECTION_CUTS_1_GENERAL = "SECTION CUTS 1 - GENERAL";
        public const string SECTION_CUTS_2_ADVANCED_LOCAL_AXES = "SECTION CUTS 2 - ADVANCED LOCAL AXES";
        public const string SECTION_CUTS_3_QUADRILATERAL_DEFINITIONS = "SECTION CUTS 3 - QUADRILATERAL DEFINITIONS";
        public const string SECTION_DESIGNER_PROPERTIES_01_GENERAL = "SECTION DESIGNER PROPERTIES 01 - GENERAL";
        public const string SECTION_DESIGNER_PROPERTIES_12_SHAPE_SOLID_RECTANGLE = "SECTION DESIGNER PROPERTIES 12 - SHAPE SOLID RECTANGLE";
        public const string SECTION_DESIGNER_PROPERTIES_30_FIBER_GENERAL = "SECTION DESIGNER PROPERTIES 30 - FIBER GENERAL";
        public const string SOLID_EDGE_CONSTRAINT_ASSIGNMENTS = "SOLID EDGE CONSTRAINT ASSIGNMENTS";
        public const string SOLID_PROPERTY_ASSIGNMENTS = "SOLID PROPERTY ASSIGNMENTS";
        public const string SOLID_PROPERTY_DEFINITIONS = "SOLID PROPERTY DEFINITIONS";
        public const string TABLES_AUTOMATICALLY_SAVED_AFTER_ANALYSIS = "TABLES AUTOMATICALLY SAVED AFTER ANALYSIS";
        public const string TENDON_LAYOUT_DATA_01_GENERAL = "TENDON LAYOUT DATA 01 - GENERAL";
        public const string TENDON_LAYOUT_DATA_02_SEGMENTS = "TENDON LAYOUT DATA 02 - SEGMENTS";
        public const string TENDON_SECTION_ASSIGNMENTS = "TENDON SECTION ASSIGNMENTS";
        public const string TENDON_SECTION_DEFINITIONS = "TENDON SECTION DEFINITIONS";


        public SAP2000Tables()
        {
            TableNames = new List<string>()
            {
                ACTIVE_DEGREES_OF_FREEDOM,
                ANALYSIS_OPTIONS,
                AREA_LOADS_UNIFORM,
                AREA_LOADS_WIND_PRESSURE_COEFFICIENTS,
                AREA_SECTION_ASSIGNMENTS,
                AREA_SECTION_PROPERTIES,
                AREA_SECTION_PROPERTY_DESIGN_PARAMETERS,
                AREA_SECTION_PROPERTY_LAYERS,
                //AREA_SECTION_PROPERTY_TIME_DEPENDENT,
                AREA_STIFFNESS_MODIFIERS,
                AUTO_COMBINATION_OPTION_DATA_01_GENERAL,
                AUTO_WAVE_3_WAVE_CHARACTERISTICS_GENERAL,
                CABLE_OUTPUT_STATION_ASSIGNMENTS,
                CABLE_SECTION_ASSIGNMENTS,
                CABLE_SECTION_DEFINITIONS,
                CABLE_SHAPE_DATA,
                CASE_STATIC_1_LOAD_ASSIGNMENTS,
                CASE_STATIC_2_NONLINEAR_LOAD_APPLICATION,
                CASE_STATIC_4_NONLINEAR_PARAMETERS,
                CASE_STATIC_5_NONLINEAR_STAGE_DEFINITIONS,
                CASE_STATIC_6_NONLINEAR_STAGE_DATA,
                CASE_STATIC_7_ADDITIONAL_CONTROLLED_DISPLACEMENTS,
                CASE_DIRECT_HISTORY_1_GENERAL,
                CASE_DIRECT_HISTORY_2_LOAD_ASSIGNMENTS,
                CASE_DIRECT_HISTORY_3_VISCOUS_PROPORTIONAL_DAMPING,
                CASE_DIRECT_HISTORY_4_INTEGRATION_PARAMETERS,
                CASE_DIRECT_HISTORY_5_NONLINEAR_PARAMETERS,
                CASE_DIRECT_HISTORY_7_MODAL_PROPORTIONAL_DAMPING,
                CASE_DIRECT_HISTORY_8_MODAL_DAMPING_OVERRIDES,
                //CASE_FREQUENCY_HISTORY_1_GENERAL,
                //CASE_FREQUENCY_HISTORY_2_LOAD_ASSIGNMENTS,
                //CASE_FREQUENCY_HISTORY_3_CONSTANT_DAMPING,
                //CASE_FREQUENCY_HISTORY_5_INTEGRATION_PARAMETERS,
                CASE_MODAL_HISTORY_1_GENERAL,
                CASE_MODAL_HISTORY_2_LOAD_ASSIGNMENTS,
                CASE_MODAL_HISTORY_3_INTERPOLATED_DAMPING,
                CASE_MODAL_HISTORY_4_PROPORTIONAL_DAMPING,
                CASE_MODAL_HISTORY_5_DAMPING_OVERRIDES,
                CASE_MODAL_HISTORY_6_NONLINEAR_PARAMETERS,
                CASE_MODAL_1_GENERAL,
                CASE_MODAL_2_LOAD_ASSIGNMENTS_EIGEN,
                CASE_MODAL_3_LOAD_ASSIGNMENTS_RITZ,
                CASE_RESPONSE_SPECTRUM_1_GENERAL,
                CASE_RESPONSE_SPECTRUM_2_LOAD_ASSIGNMENTS,
                CASE_RESPONSE_SPECTRUM_3_INTERPOLATED_DAMPING,
                CASE_RESPONSE_SPECTRUM_4_PROPORTIONAL_DAMPING,
                CASE_RESPONSE_SPECTRUM_5_DAMPING_OVERRIDES,
                CASE_RESPONSE_SPECTRUM_6_ECCENTRICITY_OVERRIDES,
                COMBINATION_DEFINITIONS,
                CONNECTIVITY_AREA,
                CONNECTIVITY_CABLE,
                CONNECTIVITY_FRAME,
                CONNECTIVITY_SOLID,
                CONNECTIVITY_LINK,
                CONNECTIVITY_TENDON,
                COORDINATE_SYSTEMS,
                DATABASE_DOCUMENTATION,
                DATABASE_FORMAT_TYPES,
                FRAME_AUTO_MESH_ASSIGNMENTS,
                FRAME_DESIGN_PROCEDURES,
                FRAME_INSERTION_POINT_ASSIGNMENTS,
                FRAME_LOAD_TRANSFER_OPTIONS,
                FRAME_LOADS_POINT,
                FRAME_LOADS_DISTRIBUTED,
                FRAME_OUTPUT_STATION_ASSIGNMENTS,
                FRAME_PROPERTY_MODIFIERS,
                FRAME_RELEASE_ASSIGNMENTS_1_GENERAL,
                FRAME_RELEASE_ASSIGNMENTS_2_PARTIAL_FIXITY,
                FRAME_SECTION_ASSIGNMENTS,
                FRAME_SECTION_PROPERTIES_01_GENERAL,
                FRAME_SECTION_PROPERTIES_02_CONCRETE_COLUMN,
                FRAME_SECTION_PROPERTIES_03_CONCRETE_BEAM,
                //FRAME_SECTION_PROPERTIES_04_AUTO_SELECT,
                //FRAME_SECTION_PROPERTIES_05_NONPRISMATIC,
                FRAME_SECTION_PROPERTIES_07_BUILT_UP_I,
                //FRAME_SECTION_PROPERTIES_10_STEEL_JOIST_GENERAL,
                //FRAME_SECTION_PROPERTIES_11_STEEL_JOIST_DATA,
                //FRAME_SECTION_PROPERTIES_13_TIME_DEPENDENT,
                //FUNCTION_PLOT_FUNCTIONS,
                FUNCTION_POWER_SPECTRAL_DENSITY_USER,
                FUNCTION_RESPONSE_SPECTRUM_USER,
                FUNCTION_RESPONSE_SPECTRUM_UBC97,
                FUNCTION_STEADY_STATE_USER,
                FUNCTION_TIME_HISTORY_COSINE,
                FUNCTION_TIME_HISTORY_RAMP,
                FUNCTION_TIME_HISTORY_SAWTOOTH,
                FUNCTION_TIME_HISTORY_SINE,
                FUNCTION_TIME_HISTORY_TRIANGULAR,
                FUNCTION_TIME_HISTORY_USER,
                GRID_LINES,
                GROUPS_1_DEFINITIONS,
                GROUPS_2_ASSIGNMENTS,
                JOINT_ADDED_MASS_ASSIGNMENTS,
                JOINT_CONSTRAINT_ASSIGNMENTS,
                JOINT_COORDINATES,
                JOINT_LOADS_FORCE,
                JOINT_LOADS_GROUND_DISPLACEMENT,
                JOINT_LOCAL_AXES_ASSIGNMENTS_1_TYPICAL,
                //JOINT_LOCAL_AXES_ASSIGNMENTS_2_ADVANCED,
                JOINT_MERGE_NUMBER_ASSIGNMENTS,
                JOINT_PANEL_ZONE_ASSIGNMENTS,
                JOINT_PATTERN_DEFINITIONS,
                JOINT_RESTRAINT_ASSIGNMENTS,
                JOINT_SPRING_ASSIGNMENTS_1_UNCOUPLED,
                JOINT_SPRING_ASSIGNMENTS_2_COUPLED,
                LINK_PROPERTY_DEFINITIONS_01_GENERAL,
                LINK_PROPERTY_DEFINITIONS_02_LINEAR,
                LINK_PROPERTY_DEFINITIONS_03_MULTILINEAR,
                LINK_PROPERTY_ASSIGNMENTS,
                LOAD_CASE_DEFINITIONS,
                LOAD_PATTERN_DEFINITIONS,
                MASS_SOURCE,
                MATERIAL_PROPERTIES_01_GENERAL,
                MATERIAL_PROPERTIES_01T_MATERIAL_TEMPERATURES,
                MATERIAL_PROPERTIES_02_BASIC_MECHANICAL_PROPERTIES,
                MATERIAL_PROPERTIES_03A_STEEL_DATA,
                MATERIAL_PROPERTIES_03B_CONCRETE_DATA,
                MATERIAL_PROPERTIES_03C_ALUMINUM_DATA,
                MATERIAL_PROPERTIES_03D_COLD_FORMED_DATA,
                MATERIAL_PROPERTIES_03E_REBAR_DATA,
                MATERIAL_PROPERTIES_03F_TENDON_DATA,
                MATERIAL_PROPERTIES_03G_OTHER_DATA,
                MATERIAL_PROPERTIES_04_USER_STRESS_STRAIN_CURVES,
                MATERIAL_PROPERTIES_06_DAMPING_PARAMETERS,
                NAMED_SETS_DATABASE_TABLES_1_GENERAL,
                NAMED_SETS_DATABASE_TABLES_2_SELECTIONS,
                OPTIONS_COLORS_DISPLAY,
                OPTIONS_COLORS_OUTPUT,
                //OVERWRITES_ALUMINUM_DESIGN_AA_ASD_2000,
                //OVERWRITES_ALUMINUM_DESIGN_AA_LRFD_2000,
                //OVERWRITES_COLD_FORMED_DESIGN_AISI_ASD96,
                //OVERWRITES_COLD_FORMED_DESIGN_AISI_LRFD96,
                //OVERWRITES_CONCRETE_DESIGN_ACI_318_08_IBC_2009,
                //OVERWRITES_CONCRETE_DESIGN_ACI_318_11,
                //OVERWRITES_CONCRETE_DESIGN_ACI_318_14,
                //OVERWRITES_CONCRETE_DESIGN_AS_3600_09,
                //OVERWRITES_CONCRETE_DESIGN_AS_3600_18,
                //OVERWRITES_CONCRETE_DESIGN_BS8110_97,
                //OVERWRITES_CONCRETE_DESIGN_CSA_A233_04,
                //OVERWRITES_CONCRETE_DESIGN_CSA_A233_14,
                //OVERWRITES_CONCRETE_DESIGN_EUROCODE_2_2004,
                //OVERWRITES_CONCRETE_DESIGN_HONG_KONG_CP_2013,
                //OVERWRITES_CONCRETE_DESIGN_INDIAN_IS_456_2000,
                //OVERWRITES_CONCRETE_DESIGN_ITALIAN_NTC_2008,
                //OVERWRITES_CONCRETE_DESIGN_KBC_2009,
                //OVERWRITES_CONCRETE_DESIGN_KBC_2016,
                //OVERWRITES_CONCRETE_DESIGN_MEXICAN_RCDF_2004,
                //OVERWRITES_CONCRETE_DESIGN_MEXICAN_RCDF_2017,
                //OVERWRITES_CONCRETE_DESIGN_NZS_3101_06,
                //OVERWRITES_CONCRETE_DESIGN_SINGAPORE_CP_65_99,
                //OVERWRITES_CONCRETE_DESIGN_TS_500_2000,
                //OVERWRITES_STEEL_DESIGN_AISC360_05_IBC2006,
                //OVERWRITES_STEEL_DESIGN_AISC_360_10,
                //OVERWRITES_STEEL_DESIGN_AISC_360_16,
                //OVERWRITES_STEEL_DESIGN_AS_4100_1998,
                //OVERWRITES_STEEL_DESIGN_BS5950_2000,
                //OVERWRITES_STEEL_DESIGN_CSA_S16_09,
                //OVERWRITES_STEEL_DESIGN_CSA_S16_14,
                //OVERWRITES_STEEL_DESIGN_EUROCODE_3_2005,
                //OVERWRITES_STEEL_DESIGN_INDIAN_IS_800_2007,
                //OVERWRITES_STEEL_DESIGN_ITALIAN_NTC_2008,
                //OVERWRITES_STEEL_DESIGN_ITALIAN_NTC_2018,
                //OVERWRITES_STEEL_DESIGN_KBC_2009,
                //OVERWRITES_STEEL_DESIGN_NZS_3404_1997,
                PREFERENCES_ALUMINUM_DESIGN_AA_ASD_2000,
                PREFERENCES_ALUMINUM_DESIGN_AA_LRFD_2000,
                PREFERENCES_COLD_FORMED_DESIGN_AISI_ASD96,
                PREFERENCES_COLD_FORMED_DESIGN_AISI_LRFD96,
                PREFERENCES_CONCRETE_DESIGN_ACI_318_08_IBC_2009,
                PREFERENCES_CONCRETE_DESIGN_ACI_318_11,
                PREFERENCES_CONCRETE_DESIGN_ACI_318_14,
                PREFERENCES_CONCRETE_DESIGN_AS_3600_09,
                PREFERENCES_CONCRETE_DESIGN_AS_3600_18,
                PREFERENCES_CONCRETE_DESIGN_BS8110_97,
                PREFERENCES_CONCRETE_DESIGN_CSA_A233_04,
                PREFERENCES_CONCRETE_DESIGN_CSA_A233_14,
                PREFERENCES_CONCRETE_DESIGN_EUROCODE_2_2004,
                PREFERENCES_CONCRETE_DESIGN_HONG_KONG_CP_2013,
                PREFERENCES_CONCRETE_DESIGN_INDIAN_IS_456_2000,
                PREFERENCES_CONCRETE_DESIGN_ITALIAN_NTC_2008,
                PREFERENCES_CONCRETE_DESIGN_KBC_2009,
                PREFERENCES_CONCRETE_DESIGN_KBC_2016,
                PREFERENCES_CONCRETE_DESIGN_MEXICAN_RCDF_2004,
                PREFERENCES_CONCRETE_DESIGN_MEXICAN_RCDF_2017,
                PREFERENCES_CONCRETE_DESIGN_NZS_3101_06,
                PREFERENCES_CONCRETE_DESIGN_SINGAPORE_CP_65_99,
                PREFERENCES_CONCRETE_DESIGN_TS_500_2000,
                PREFERENCES_DIMENSIONAL,
                PREFERENCES_STEEL_DESIGN_AISC360_05_IBC2006,
                PREFERENCES_STEEL_DESIGN_AISC_360_10,
                PREFERENCES_STEEL_DESIGN_AISC_360_16,
                PREFERENCES_STEEL_DESIGN_AS_4100_1998,
                PREFERENCES_STEEL_DESIGN_BS5950_2000,
                PREFERENCES_STEEL_DESIGN_CSA_S16_09,
                PREFERENCES_STEEL_DESIGN_CSA_S16_14,
                PREFERENCES_STEEL_DESIGN_EUROCODE_3_2005,
                PREFERENCES_STEEL_DESIGN_INDIAN_IS_800_2007,
                PREFERENCES_STEEL_DESIGN_ITALIAN_NTC_2008,
                PREFERENCES_STEEL_DESIGN_ITALIAN_NTC_2018,
                PREFERENCES_STEEL_DESIGN_KBC_2009,
                PREFERENCES_STEEL_DESIGN_NZS_3404_1997,
                PROGRAM_CONTROL,
                PROJECT_INFORMATION,
                REBAR_SIZES,
                SECTION_CUTS_1_GENERAL,
                SECTION_CUTS_2_ADVANCED_LOCAL_AXES,
                SECTION_CUTS_3_QUADRILATERAL_DEFINITIONS,
                SECTION_DESIGNER_PROPERTIES_01_GENERAL,
                SECTION_DESIGNER_PROPERTIES_12_SHAPE_SOLID_RECTANGLE,
                SECTION_DESIGNER_PROPERTIES_30_FIBER_GENERAL,
                SOLID_EDGE_CONSTRAINT_ASSIGNMENTS,
                SOLID_PROPERTY_ASSIGNMENTS,
                SOLID_PROPERTY_DEFINITIONS,
                TABLES_AUTOMATICALLY_SAVED_AFTER_ANALYSIS,
                TENDON_LAYOUT_DATA_01_GENERAL,
                TENDON_LAYOUT_DATA_02_SEGMENTS,
                TENDON_SECTION_ASSIGNMENTS,
                TENDON_SECTION_DEFINITIONS,
            };
        }
    }
}
